export const ENDPOINTS = {
  auth: {
    signup: "/auth/signup",
    verifyEmail: "/auth/verify-email",
    login: "/auth/login",
    forgotPassword: "/auth/forgot-password",
    verifyResetOtp: "/auth/verify-reset-otp",
    resetPassword: "/auth/reset-password",
    logout: "/auth/logout",
    me: "/auth/me",
  },
  shop: {
    products: {
      getAllProducts: "/product/getAllProducts",
      getFlatProducts: "/product/getFlatProducts?limit=3&page=1",
      searchProducts: "/product/searchProducts?q=p&limit=10",
      getProductById: "/product/getProductById/:id",
      addProduct: "/product/addProduct",
      updateProduct: "/product/updateProduct/:id",
      deleteProduct: "/product/deleteProduct/:id",
    },
    categories: {
      addCategory: "/category/addCategory",
      getAllCategories: "/category/getAllCategories",
      getCategoryById: "/category/getCategoryById/:id",
      getFlatCategories: "/category/getFlatCategories",
      updateCategory: "/category/updateCategory/:id",
      deleteCategory: "/category/deleteCategory/:id",
    },
    cart: {
      addToCart: "/cart/addToCart",
      getCart: "/cart/getCart",
      getCartCount: "/cart/getCartCount",
      removeFromCart: "/cart/removeFromCart",
      clearCart: "/cart/clearCart",
      updateCart: "/cart/updateCart",
      deleteCart: "/cart/deleteCart",
    },
    checkout: {
      createOrder: "/checkout/createOrder",
      getOrderById: "/checkout/getOrderById/:id",
    },
    account: {
      getAddresses: "/account/getAddresses",
      addAddress: "/account/addAddress",
      updateAddress: "/account/updateAddress/:id",
      getProfile: "/account/getProfile",
      updateProfile: "/account/updateProfile",
      deleteAddress: "/account/deleteAddress/:id",
      getMyOrders: "/account/getMyOrders",
    },
  },
  admin: {},
  hotels: {},
  flights: {},
};
